version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app  # Mount local code into container for live dev
    command: >
      sh -c "
      if [ \"$DEBUG\" = \"True\" ]; then
        python manage.py runserver 0.0.0.0:8000;
      else
        gunicorn order_management.wsgi:application --bind 0.0.0.0:8000;
      fi
      "

  db:
    image: postgres:16
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

volumes:
  pgdata:
